var mongoose = require("mongoose");
var Schema = mongoose.Schema;

var dividentSettingsSchema = new Schema({
  description: { type: String, default: "" },
  slot_cade: { type: Number, default: 0 },
  inhouse_cade: { type: Number, default: 0 },
  slot_cade_eth: { type: Number, default: 0 },
  inhouse_cade_eth: { type: Number, default: 0 },
  slot_cade_matic: { type: Number, default: 0 },
  inhouse_cade_matic: { type: Number, default: 0 },
  min_freezeAmount: { type: String, default: "" },
  min_withdrawAmount: { type: String, default: "" },
  max_withdrawAmount: { type: String, default: "" },
  user_percent: { type: String, default: "" },
  admin_percent: { type: String, default: "" },
  team_percent: { type: String, default: "" },
  team_amount: { type: Number, default: 0 },
  admin_amount: { type: Number, default: 0 },
  team_amount_eth: { type: Number, default: 0 },
  admin_amount_eth: { type: Number, default: 0 },
  team_amount_matic: { type: Number, default: 0 },
  admin_amount_matic: { type: Number, default: 0 },
  cashback_share: { type: Number, default: 0 },
  mint_amount: { type: Number, default: 0 },
  expiry_amount: { type: Number, default: 0 },
  expirystake_amount: { type: Number, default: 0 },
  expiryeth_amount: { type: Number, default: 0 },
  expirymatic_amount: { type: Number, default: 0 },
  pool_amount: { type: Number, default: 0 },
  fake_pool_amount: { type: Number, default: 0 },
  eth_pool_amount: { type: Number, default: 0 },
  eth_fake_pool_amount: { type: Number, default: 0 },
  matic_pool_amount: { type: Number, default: 0 },
  matic_fake_pool_amount: { type: Number, default: 0 },
  linked_addr_con: { type: String },
  wager_pool_amount: { type: Number, default: 0 },
  winner_pool_amount: { type: Number, default: 0 },
  wager_pool_amount_eth: { type: Number, default: 0 },
  winner_pool_amount_eth: { type: Number, default: 0 },
  wager_pool_amount_matic: { type: Number, default: 0 },
  winner_pool_amount_matic: { type: Number, default: 0 },
  claim_fee_amount: { type: Number, default: 0 },
  withdraw_expiry: { type: String, default: "" },
  user_multiplier_mining_limit: { type: Number, default: 0 },
  matic_trx: { type: Number, default: 0 },
  eth_trx: { type: Number, default: 0 },
  trx_eur: { type: Number, default: 0 },
  matic_eur: { type: Number, default: 0 },
  eth_eur: { type: Number, default: 0 },
  shop_transactions_interval_limit_seconds: { type: Number, default: 0 },
  createddate: { type: Date, default: Date.now },
});
module.exports = mongoose.model(
  "DividentSetting",
  dividentSettingsSchema,
  "DividentSetting"
);
